name: license_plates
channels:
  - defaults
dependencies:
  - python
  - conda-forge::opencv
  - conda-forge::matplotlib
  - conda-forge::scikit-image
  - conda-forge::imutils
  - conda-forge::scikit-learn
  - pytorch::pytorch
  - pytorch::torchvision
  - pandas
  - conda-forge::pytesseract